version: '3.7'

networks:
  project-network:
    driver: bridge

volumes:
  db:
    driver: local

services:
  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME:-project}_nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html:ro
      - ${NGINX_SERVER_CONFIG_FILE:-./.docker/nginx/config/developer.conf}:/etc/nginx/conf.d/default.conf:ro
    env_file:
      - ./.env
      - ./.env.local
    depends_on:
      - php
    networks:
      - project-network

  php:
    image: php:8.0.0-fpm
    container_name: ${PROJECT_NAME:-project}_php
    ports:
      - "9000:9000"
      - "2222:22" # ssh connection with container
      - "9003:9003" # xdebug
    volumes:
      - ./src:/var/www/html:rw
      - ~/.composer:/var/www/.composer:rw
      - ~/.npm:/var/www/.npm:rw
    env_file:
      - ./.env
      - ./.env.local
    environment:
      - PHP_MEMORY_LIMIT=2048mb
      - XDEBUG_ENABLED=0
    depends_on:
      - db
    links:
      - db
    networks:
      - project-network

  db:
    image: mysql:5.7
    container_name: ${PROJECT_NAME:-project}_db
    ports:
      - 3300:3306
    env_file:
      - ./.env
      - ./.env.local
    volumes:
      - db:/var/lib/mysql:rw
    networks:
      project-network:
        aliases:
          - db-server
