version: '3.7'

networks:
  project-network:
    driver: bridge

volumes:
  db:
    driver: local

services:
  nginx:
    image: nginx:1.21.6-alpine
    container_name: ${PROJECT_NAME:-project}_nginx
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html:ro
      - ./build/nginx/templates:/etc/nginx/templates
      - ../var/log/nginx:/var/log/nginx/
    environment:
      - SITE_ROOT=/var/www/html/public
      - NGINX_PORT=80
      - NGINX_HOST=localhost
    env_file:
      - ../.env
      - ../.env.local
    depends_on:
      - php
    networks:
      - project-network

  php:
    build:
      context: ./build/php/
    container_name: ${PROJECT_NAME:-project}_php
    restart: on-failure
    user: "1000:1000"
    ports:
      - "9000:9000"
      - "2222:22" # ssh connection with container
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../:/var/www/html:rw
      - ~/.composer:/var/www/.composer:rw
      - ~/.npm:/var/www/.npm:rw
    env_file:
      - ../.env
      - ../.env.local
    environment:
      - PHP_MEMORY_LIMIT=2048mb
    depends_on:
      - db
    links:
      - db
    networks:
      - project-network

  db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME:-project}_db
    restart: on-failure
    ports:
      - "3300:3306"
    env_file:
      - ../.env
      - ../.env.local
    volumes:
      - db:/var/lib/mysql:rw
    networks:
      project-network:
        aliases:
          - db-server
