version: '3.7'

networks:
  project-network:
    driver: bridge

volumes:
  db:
    driver: local

services:
  nginx:
    image: nginx:1.19.6-alpine
    container_name: ${PROJECT_NAME:-project}_nginx
    ports:
      - "80:80"
    volumes:
      - ../:/app:ro
      - /app/vendor
      - ./build/nginx/templates:/etc/nginx/templates
      - ../var/log/nginx:/var/log/nginx/
    environment:
      - SITE_ROOT=/app/public
      - NGINX_PORT=80
      - NGINX_HOST=website.local
    env_file:
      - ../.env
      - ../.env.local
    depends_on:
      - php
    networks:
      - project-network

  php:
    build:
      context: ./build/php/
    container_name: ${PROJECT_NAME:-project}_php
    ports:
      - "9000:9000"
    volumes:
      - ../:/app:rw
      - ./.docker/build/php/php.ini:/etc/php/8.0/fpm/conf.d/custom.ini
      - ~/.composer:/var/www/.composer:rw
      - ~/.npm:/var/www/.npm:rw
    env_file:
      - ../.env
      - ../.env.local
    environment:
      - PHP_MEMORY_LIMIT=2048mb
      - XDEBUG_ENABLED=0
    depends_on:
      - db
    links:
      - db
    networks:
      - project-network

  db:
    image: mysql:5.7
    container_name: ${PROJECT_NAME:-project}_db
    ports:
      - 3300:3306
    env_file:
      - ../.env
      - ../.env.local
    volumes:
      - db:/var/lib/mysql:rw
    networks:
      project-network:
        aliases:
          - db-server
